server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #≈‰÷√Git≤÷ø‚µƒµÿ÷∑
          uri: https://git.oschina.net/itmuch/spring-cloud-config-repo
          username: 447055767@qq.com
          password: a25059766