server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-feign-loggin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      microservice-provider-user:
        loggerLevel: full
loggin:
  level:
    com.itmuch.cloud.study.user.service.UserFeignClient: DEBUG   #将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG做出响应\

