server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size£¬Ä¬ÈÏ1M
      max-request-size: 2500Mb   # Max request size£¬Ä¬ÈÏ10M
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000
ribbon:
    ConnectTimeout: 30000
    ReadTimeout: 600000